// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bolt12.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const fetchBolt12Invoice = `-- name: FetchBolt12Invoice :one
SELECT b.offer_id, b.invreq_payer_id, b.invreq_quantity, o.hash AS offer_hash
FROM bolt12_invoices b
LEFT JOIN offers o ON o.id = b.offer_id
WHERE b.invoice_id = $1
`

type FetchBolt12InvoiceRow struct {
	OfferID        sql.NullInt64
	InvreqPayerID  []byte
	InvreqQuantity sql.NullInt64
	OfferHash      []byte
}

func (q *Queries) FetchBolt12Invoice(ctx context.Context, invoiceID int64) (FetchBolt12InvoiceRow, error) {
	row := q.db.QueryRowContext(ctx, fetchBolt12Invoice, invoiceID)
	var i FetchBolt12InvoiceRow
	err := row.Scan(
		&i.OfferID,
		&i.InvreqPayerID,
		&i.InvreqQuantity,
		&i.OfferHash,
	)
	return i, err
}

const fetchBolt12Payment = `-- name: FetchBolt12Payment :one
SELECT k.idempotency_key, k.payment_id, k.offer_hash, k.params_hash,
    p.payment_identifier
FROM bolt12_payments k
LEFT JOIN payments p ON p.id = k.payment_id
WHERE k.idempotency_key = $1
`

type FetchBolt12PaymentRow struct {
	IdempotencyKey    []byte
	PaymentID         sql.NullInt64
	OfferHash         []byte
	ParamsHash        []byte
	PaymentIdentifier []byte
}

func (q *Queries) FetchBolt12Payment(ctx context.Context, idempotencyKey []byte) (FetchBolt12PaymentRow, error) {
	row := q.db.QueryRowContext(ctx, fetchBolt12Payment, idempotencyKey)
	var i FetchBolt12PaymentRow
	err := row.Scan(
		&i.IdempotencyKey,
		&i.PaymentID,
		&i.OfferHash,
		&i.ParamsHash,
		&i.PaymentIdentifier,
	)
	return i, err
}

const fetchBolt12PaymentIDsByOffer = `-- name: FetchBolt12PaymentIDsByOffer :many
SELECT k.payment_id
FROM bolt12_payments k
WHERE k.offer_hash = $1 AND k.payment_id IS NOT NULL
ORDER BY k.payment_id
`

func (q *Queries) FetchBolt12PaymentIDsByOffer(ctx context.Context, offerHash []byte) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, fetchBolt12PaymentIDsByOffer, offerHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt64
	for rows.Next() {
		var payment_id sql.NullInt64
		if err := rows.Scan(&payment_id); err != nil {
			return nil, err
		}
		items = append(items, payment_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBolt12Invoice = `-- name: InsertBolt12Invoice :exec
INSERT INTO bolt12_invoices (
    invoice_id, offer_id, invreq_payer_id, invreq_quantity
) VALUES (
    $1, $2, $3, $4
)
`

type InsertBolt12InvoiceParams struct {
	InvoiceID      int64
	OfferID        sql.NullInt64
	InvreqPayerID  []byte
	InvreqQuantity sql.NullInt64
}

func (q *Queries) InsertBolt12Invoice(ctx context.Context, arg InsertBolt12InvoiceParams) error {
	_, err := q.db.ExecContext(ctx, insertBolt12Invoice,
		arg.InvoiceID,
		arg.OfferID,
		arg.InvreqPayerID,
		arg.InvreqQuantity,
	)
	return err
}

const upsertBolt12Payment = `-- name: UpsertBolt12Payment :exec
INSERT INTO bolt12_payments (
    idempotency_key, payment_id, offer_hash, params_hash, created_at
) VALUES (
    $1, $2, $3, $4, $5
) ON CONFLICT (idempotency_key) DO UPDATE SET
    payment_id = excluded.payment_id
`

type UpsertBolt12PaymentParams struct {
	IdempotencyKey []byte
	PaymentID      sql.NullInt64
	OfferHash      []byte
	ParamsHash     []byte
	CreatedAt      time.Time
}

func (q *Queries) UpsertBolt12Payment(ctx context.Context, arg UpsertBolt12PaymentParams) error {
	_, err := q.db.ExecContext(ctx, upsertBolt12Payment,
		arg.IdempotencyKey,
		arg.PaymentID,
		arg.OfferHash,
		arg.ParamsHash,
		arg.CreatedAt,
	)
	return err
}
