// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: invoice_requests.sql

package sqlc

import (
	"context"
	"time"
)

const fetchInvoiceRequestsByOfferID = `-- name: FetchInvoiceRequestsByOfferID :many
SELECT id, offer_id, invreq_bytes, invoice_bytes, payer_key, created_at
FROM invoice_request_store
WHERE offer_id = $1
ORDER BY created_at DESC
`

// Fetch all invoice request records for a given offer, ordered by
// creation time descending.
func (q *Queries) FetchInvoiceRequestsByOfferID(ctx context.Context, offerID []byte) ([]InvoiceRequestStore, error) {
	rows, err := q.db.QueryContext(ctx, fetchInvoiceRequestsByOfferID, offerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceRequestStore
	for rows.Next() {
		var i InvoiceRequestStore
		if err := rows.Scan(
			&i.ID,
			&i.OfferID,
			&i.InvreqBytes,
			&i.InvoiceBytes,
			&i.PayerKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertInvoiceRequest = `-- name: InsertInvoiceRequest :one
INSERT INTO invoice_request_store (
    offer_id,
    invreq_bytes,
    invoice_bytes,
    payer_key,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id
`

type InsertInvoiceRequestParams struct {
	OfferID      []byte
	InvreqBytes  []byte
	InvoiceBytes []byte
	PayerKey     []byte
	CreatedAt    time.Time
}

// Insert an outgoing invoice request record. invoice_bytes is NULL
// until the reply arrives.
func (q *Queries) InsertInvoiceRequest(ctx context.Context, arg InsertInvoiceRequestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertInvoiceRequest,
		arg.OfferID,
		arg.InvreqBytes,
		arg.InvoiceBytes,
		arg.PayerKey,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateInvoiceRequestInvoice = `-- name: UpdateInvoiceRequestInvoice :exec
UPDATE invoice_request_store
SET invoice_bytes = $1
WHERE id = $2
`

type UpdateInvoiceRequestInvoiceParams struct {
	InvoiceBytes []byte
	ID           int64
}

// Set the invoice_bytes on an existing record after the invoice
// reply arrives.
func (q *Queries) UpdateInvoiceRequestInvoice(ctx context.Context, arg UpdateInvoiceRequestInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, updateInvoiceRequestInvoice, arg.InvoiceBytes, arg.ID)
	return err
}
