// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: offers.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const disableOffer = `-- name: DisableOffer :execresult
UPDATE offers
SET is_disabled = TRUE
WHERE id = $1
`

func (q *Queries) DisableOffer(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, disableOffer, id)
}

const enableOffer = `-- name: EnableOffer :execresult
UPDATE offers
SET is_disabled = FALSE
WHERE id = $1
`

func (q *Queries) EnableOffer(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, enableOffer, id)
}

const getOfferByID = `-- name: GetOfferByID :one
SELECT id, offer_id, encoded, issuer_node_id, description, amount_msat, currency, absolute_expiry, quantity_max, is_disabled, created_at
FROM offers
WHERE id = $1
`

func (q *Queries) GetOfferByID(ctx context.Context, id int64) (Offer, error) {
	row := q.db.QueryRowContext(ctx, getOfferByID, id)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.Encoded,
		&i.IssuerNodeID,
		&i.Description,
		&i.AmountMsat,
		&i.Currency,
		&i.AbsoluteExpiry,
		&i.QuantityMax,
		&i.IsDisabled,
		&i.CreatedAt,
	)
	return i, err
}

const getOfferByOfferID = `-- name: GetOfferByOfferID :one
SELECT id, offer_id, encoded, issuer_node_id, description, amount_msat, currency, absolute_expiry, quantity_max, is_disabled, created_at
FROM offers
WHERE offer_id = $1
`

func (q *Queries) GetOfferByOfferID(ctx context.Context, offerID []byte) (Offer, error) {
	row := q.db.QueryRowContext(ctx, getOfferByOfferID, offerID)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.OfferID,
		&i.Encoded,
		&i.IssuerNodeID,
		&i.Description,
		&i.AmountMsat,
		&i.Currency,
		&i.AbsoluteExpiry,
		&i.QuantityMax,
		&i.IsDisabled,
		&i.CreatedAt,
	)
	return i, err
}

const insertOffer = `-- name: InsertOffer :one
INSERT INTO offers (
    offer_id, encoded, issuer_node_id, description, amount_msat,
    currency, absolute_expiry, quantity_max, is_disabled, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id
`

type InsertOfferParams struct {
	OfferID        []byte
	Encoded        string
	IssuerNodeID   []byte
	Description    sql.NullString
	AmountMsat     sql.NullInt64
	Currency       sql.NullString
	AbsoluteExpiry sql.NullInt64
	QuantityMax    sql.NullInt64
	IsDisabled     bool
	CreatedAt      time.Time
}

func (q *Queries) InsertOffer(ctx context.Context, arg InsertOfferParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertOffer,
		arg.OfferID,
		arg.Encoded,
		arg.IssuerNodeID,
		arg.Description,
		arg.AmountMsat,
		arg.Currency,
		arg.AbsoluteExpiry,
		arg.QuantityMax,
		arg.IsDisabled,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listOffers = `-- name: ListOffers :many
SELECT id, offer_id, encoded, issuer_node_id, description, amount_msat, currency, absolute_expiry, quantity_max, is_disabled, created_at
FROM offers
WHERE (NOT $1 OR is_disabled = FALSE)
ORDER BY id ASC
LIMIT $3 OFFSET $2
`

type ListOffersParams struct {
	ActiveOnly interface{}
	NumOffset  int32
	NumLimit   int32
}

// ListOffers returns offers ordered by creation time. The caller supplies
// Go-side defaults when a filter is not needed:
//
//	include_disabled → true  (include all offers)
func (q *Queries) ListOffers(ctx context.Context, arg ListOffersParams) ([]Offer, error) {
	rows, err := q.db.QueryContext(ctx, listOffers, arg.ActiveOnly, arg.NumOffset, arg.NumLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.OfferID,
			&i.Encoded,
			&i.IssuerNodeID,
			&i.Description,
			&i.AmountMsat,
			&i.Currency,
			&i.AbsoluteExpiry,
			&i.QuantityMax,
			&i.IsDisabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
